### ISSUE TITLE
Логика 

### ISSUE THREAD

**Issue by kisate** [lunakoly/Brootkiddie#7]
- [x] Переделать майнинг крипты
- [x] Переделать распространение
- [x] Распределение (да, ты его все-таки должен написать, кому же еще?)
- [x] Комбинации скриптов в вирусе

**Comment by vsalavatov** [comment]
@kisate, а что не так с майнингом?

**Comment by vsalavatov** [comment]
https://goo.gl/R7Vc24
normalized [0; 1] -> [0; 1] sigmoid function
